accounts:
  ecadlabs:
    # mv1R7T3AKpmTEzkwPuUu14rewEjAz2qbT5tw
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  smartpy:
    # mv1EidjD8sWLCZeVqJdCfd1AXmTnkAEe1dGF
    key: edpkuyuJirNU14hEma1u7f3Qhx7uHZxzuXDyvmjRwaAsFFFqYGkzHx
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  tezosil:
    # mv1Ht4BQHcZX5qfJTMQQfp54mXrtcNagwUAL
    key: edpkvQj8r3YigN6QFsDRaKQCoxDNhKK4whDUkFkw6Gom36d86uhEbv
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  pirbo:
    # mv1C6KuPzs92LTENfXUPXq1oNxvaLjxJ9p8b
    key: edpkvaQpRgsSGPJSY91sjNArLMgpTUHmmfkvuSekwos43uze2H2EFM
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  andrewk:
    key: edpkvNGUd3xcBNmPWRbXJoS6WEvxu1BVoWjHr7ab7QoAJFFqhx9tkR
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  blockwatch:
    # mv1Qu7ZshVnDJJbdaGP1z2KQRc4cPdwRAFNQ
    key: edpktqRmZsGN2WEyghfqrZvn8c7xmA1xs3vDta71CsCjtHiSRMkG1z
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  marco:
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  fifthelement:
    key: edpkujqmLUVGNbSNZV7CBMdtXAMGTTwJDQoXp2aRGrotys51rYvaRi
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  utdrmac:
    # mv1KX4ARPrWmCvFzqCRqM1pE7XMy3YkWa6Mv
    key: edpkvWPKvk8A8tk97Sr8CbyKJLekuHYwQ5R2rJ3Qe23jvtewaRAdYp
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  primate:
    # mv1EX2Q5UbjGWfndYQph2EvjcA1XjYSGttGa
    key: edpkvM7PAJiTMTAeRB1W77U5jF17aCV1vkBoKPScs8vmAd56t2BE72
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  N1029676:
    # mv1ANyMiEjYnkfd1ev3eQkn6VG9yUQuprfNY
    key: edpkuZ6pf5esZLnVJ7XGZbfQ6s9yFsrGW49nhrRVrCZ6ghqRvGR1n5
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  vincent_xtzmaster:
    # mv18DaXmm6RTKsBUpX1BZcpL3w7PUvjKVPWA
    key: edpkuVw1DAAJ1bucCkNJ48e9L8Md8meXogKnMUp1Z6sey1NFhCxmvU
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  neoktalabs_julien:
    # mv1UbfgGattRWGeTqVVNLPo3Kt2Es6wRKiGq
    key: edpkv99446esWVTgGSNsfeZCpeLYbq1e69tae3Fpw22GXcMHQeRSVg
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  coredump:
    # mv1K9acNerxTy6EpieyEEb4bQAr83JABwCJ8
    key: edpkttKzcNNCjanS2De2Nagnpg9Bk1SoNhxDC1hqCFvHHFjfeeBK1m
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  german:
    # german wants to be a baker, but not bootstrap
    # mv1FdnkStDVAwUpcNeruHcBf8bVnD6rvNSik
    key: edpktjm6QS9TwK6z9VX36Gucknwag94EzfCiu741i8q373W4V4y24R
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "2000000000000"
  ping:
    # mv1AHfXjwzJ4NzWFjwdia9iBpWmLSu6rm2n8
    key: edpkvZcJNTNG3q4A4N42eNPPCtUDT5jffMCYwiD7QLzRGZ4CQR8pyj
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  saroupille:
    # françois wants to be a baker, but not bootstrap
    # mv1CtdUBCLRpBziu4Xkuow3Xx2kjbhTieU5Z
    key: edpkvMBeXH4h8H97b8qfPkv2mA9TE6McfsffLGgG2Jg5nhUESaVt5J
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "2000000000000"
  saroupille2:
    # françois wants to be a baker, but not bootstrap
    # mv1MwkWM8AVmfKNg1jGBtxCMUk1qxeaGtzCz
    key: edpkueS4HbicvgHo1Y9uPp6ZaZ8kgMJBJg2uB4Zm539Wf7qvJA5g1U
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "2000000000000"
  victor:
    # mv1J65tSuttRUSKEB8y2QEvJdjdWmMHGX1ct
    key: edpkujMeTHyUEK4gqCBXHDL9yXYiHnJJ4C58AHnmgAKyfFZXcBRngB
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "2000000000000"
  mv1Fewfk:
    # mv1FewfkkANV9UrmmgqPdcCPwwV7XftdvhLS 
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  julien:
    # for stress testing
    # mv1C666oQekupeXexgguj5AwnqK5mVRTKek6
    key: edpktnArvYkSArFUGiBN4cmDmor9qwyTFCbAKEMbeSdT3z563SdTXm
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # mv185FmHGAimjbxkFEz8fcfeNHJ9pFwLquQW
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "500000000000000"
  oxheadbaker:
    # Oxhead Alpha's baker hosted in testnets.mavryk.org infra
    # mv1UAzbGkMvuCr7ufR6Z4NxykCn2aj5qTUjm
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # mv1UBRZEJQ211zucHsXAn19FzZTeov3DSmbm
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public

node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_HANGZHOUNET_2021-11-04T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesis7e8c4d4snJW
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2021-11-04T15:00:00Z"
  user_activated_upgrades:
    - level: 8191
      replacement_protocol: PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx

bootstrap_peers:
  - hangzhounet.smartpy.io
  - hangzhounet.kaml.fr
  - hangzhounet.boot.tez.ie

images:
  octez: tezos/tezos:v12.2

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - baker
      - endorser
      - octez_node
      - accuser
    storage_size: 80Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

activation:
  protocol_hash: PtGRANADsDU8R9daYKAgWnQYAJ64omN1o3KMGVCykShA97vQbvV
  protocol_parameters:
     preserved_cycles: 3
     blocks_per_cycle: 4096
     blocks_per_commitment: 32
     blocks_per_roll_snapshot: 256
     blocks_per_voting_period: 20480
     time_between_blocks:
       - "20"
       - "10"
     endorsers_per_block: 256
     hard_gas_limit_per_operation: "1040000"
     hard_gas_limit_per_block: "5200000"
     proof_of_work_threshold: "70368744177663"
     tokens_per_roll: "8000000000"
     seed_nonce_revelation_tip: "125000"
     origination_size: 257
     block_security_deposit: "640000000"
     endorsement_security_deposit: "2500000"
     baking_reward_per_endorsement:
       - "78125"
       - "11719"
     endorsement_reward:
       - "78125"
       - "52083"
     cost_per_byte: "250"
     hard_storage_limit_per_operation: "60000"
     quorum_min: 2000
     quorum_max: 7000
     min_proposal_quorum: 500
     initial_endorsers: 192
     delay_per_missing_endorsement: "2"
     liquidity_baking_escape_ema_threshold: 100000
     liquidity_baking_subsidy: '2500000'
     liquidity_baking_sunset_level: 525600
     minimal_block_delay: '15'
     michelson_maximum_type_size: 1000

protocols:
  - command: 011-PtHangz2

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: "https://hangzhounet.xtz-shots.io/archive-tarball"
