images:
  mavrykFaucet: ghcr.io/mavryk-network/mavryk-faucet:main
  mavrykFaucetBackend: ghcr.io/mavryk-network/mavryk-faucet-backend:main

# Frontend app configuration. You can optionally deploy only the faucet backend.
enableUI: true
config:
  application:
    name: "Mavryk Dailynet faucet"
    googleCaptchaSiteKey: "" #filled in by pulumi
    backendUrl: "" # filled in by pulumi
    githubRepo: https://github.com/mavryk-network/mavryk-faucet
  network:
    name: # filled in by pulumi
    rpcUrl: # filled in by pulumi
    faucetAddress: mv1NRjkhmeavqVVh716ephuXmaXGe7Y6UyzQ
    viewer: https://dailynet.tzstats.com

# Value the server sets for the "Access-Control-Allow-Origin" header for CORS.
authorizedHost: "" # filled in by pulumi
# RPC url for the faucet backend. Default value assumes mavryk-k8s created an RPC
# service in the same namespace. If not set, defaults to `config.network.rpcUrl`.
backendRpcUrl: http://mavryk-node-rpc:8732
# If the backend requires CAPTCHA tokens to be submitted.
enableCaptcha: true

# The minimum Tez allowed per request.
minTez: 1
# The maximum Tez allowed per request.
maxTez: 1000000

disableChallenges: false
# Minimum number of challenges required for the minimum Tez request.
minChallenges: 1
# Maximum number of challenges required for the maximum Tez request.
# 550 challenges should take ~10m.
maxChallenges: 550
# Maximum number of challenges required for the maximum Tez request when a
# captcha is used.
# 26 challenges should take ~2m.
maxChallengesWithCaptcha: 26
# How many bytes the challenge string should be.
challengeSize: 2048
# Difficulty level for challenges.
difficulty: 4

redis:
  url: redis://redis-master:6379

ingress:
  enabled: true
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
  host: "" # faucet fqdn, filled in by pulumi
  tls: [] # filled in by pulumi

# Secrets
googleCaptchaSecretKey: "" # filled in by pulumi
faucetPrivateKey: "" # filled in by pulumi
