tezos_k8s_images:
  utils: ghcr.io/mavryk-network/mavryk-k8s-utils:6.25.0
signers:
  tezos-signer-0:
    sign_for_accounts:
    - teztnetsbaker

node_config_network:
  activation_account_name: teztnetsbaker
  genesis:
    block: BMFCHw1mv3A71KpTuGD3MoFnkHk9wvTYjUzuR9QqiUumKGFG6pM
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
  dal_config:
    activated: true
    use_mock_srs_for_testing:
      redundancy_factor: 16
      page_size: 4096
      slot_size: 16384
      number_of_shards: 512

protocols:
  - command: alpha
    vote:
      liquidity_baking_toggle_vote: "pass"
      adaptive_issuance_vote: "on"

activation:
  protocol_hash: ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 128
    blocks_per_commitment: 16
    blocks_per_stake_snapshot: 64
    cycles_per_voting_period: 1
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '5200000'
    proof_of_work_threshold: '-1'
    minimal_stake: '6000000000'
    minimal_frozen_stake: '600000000'
    adaptive_issuance_launch_ema_threshold: 10000000
    adaptive_issuance_activation_vote_enable: false
    autostaking_enable: true
    global_limit_of_staking_over_baking: 5
    edge_of_staking_over_delegation: 2
    adaptive_rewards_params:
      issuance_ratio_min:
        numerator: "1"
        denominator: "200"
      issuance_ratio_max:
        numerator: "1"
        denominator: "10"
      max_bonus: "50000000000000"
      growth_rate:
        numerator: "1"
        denominator: "100"
      center_dz:
        numerator: "1"
        denominator: "2"
      radius_dz:
        numerator: "1"
        denominator: "50"
    issuance_weights:
      base_total_issued_per_minute: "85007812"
      baking_reward_fixed_portion_weight: 5120
      baking_reward_bonus_weight: 5120
      attesting_reward_weight: 10240
      liquidity_baking_subsidy_weight: 1280
      vdf_revelation_tip_weight: 1
      seed_nonce_revelation_tip_weight: 1
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '250'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_toggle_ema_threshold: 100000
    max_operations_time_to_live: 120
    minimal_block_delay: "7"
    delay_increment_per_round: "7"
    consensus_rights_delay: 3
    delegate_parameters_activation_delay: 3
    blocks_preservation_cycles: 3
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    limit_of_delegation_over_baking: 9
    percentage_of_frozen_deposits_slashed_per_double_baking: 7
    percentage_of_frozen_deposits_slashed_per_double_attestation: 50
    cache_script_size: 100000000
    cache_stake_distribution_cycles: 8
    cache_sampler_state_cycles: 8
    nonce_revelation_threshold: 32
    vdf_difficulty: '10000000'
    dal_parametric:
      feature_enable: true
      number_of_slots: 16
      number_of_shards: 512
      attestation_lag: 3
      attestation_threshold: 1
      slot_size: 16384
      redundancy_factor: 16
      page_size: 4096
      blocks_per_epoch: 32
    smart_rollup_private_enable: true
    smart_rollup_riscv_pvm_enable: true
    smart_rollup_origination_size: 6314
    smart_rollup_challenge_window_in_blocks: 40
    smart_rollup_stake_amount: "32000000"
    smart_rollup_commitment_period_in_blocks: 20
    smart_rollup_max_lookahead_in_blocks: 30000
    smart_rollup_max_active_outbox_levels: 20160
    smart_rollup_max_outbox_messages_per_level: 100
    smart_rollup_number_of_sections_in_dissection: 32
    smart_rollup_timeout_period_in_blocks: 500
    smart_rollup_max_number_of_cemented_commitments: 5
    smart_rollup_max_number_of_parallel_games: 32
    smart_rollup_arith_pvm_enable: true
    smart_rollup_reveal_activation_level:
      raw_data:
        Blake2B: 0
      metadata: 0
      dal_page: 0
      dal_parameters: 0
    zk_rollup_enable: true
    zk_rollup_origination_size: 4000
    zk_rollup_min_pending_to_process: 10
    zk_rollup_max_ticket_payload_size: 2048
    direct_ticket_spending_enable: true
  bootstrap_parameters:
    bootstrap_smart_rollups:
    - address: "sr1RYurGZtN8KNSpkMcCt9CgWeUaNkzsAfXf"
      pvm_kind: "wasm_2_0_0"
      kernel: "fromfile#/usr/local/share/tezos/evm_kernel/evm_installer.wasm"
      parameters_ty:
        prim: pair
        args:
        - prim: pair
          args:
          - prim: bytes
          - prim: ticket
            args:
            - prim: unit
        - prim: pair
          args:
          - prim: nat
          - prim: bytes
nodes:
  tezos-baking-node:
    env:
      all:
        TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"
    instances:
      - bake_using_accounts:
          - teztnetsbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
          metrics_addr: ["0.0.0.0:9932"]
        is_bootstrap_node: true
        identity:
          # hard-coded identity - saves 1-2 minutes on daily cron
          peer_id: idtfXVcgRe6enZGqfZh7NJPW88dMpR
          public_key:
             c3e27605e7b4b7f4c75c7d54092b691badc24fc6ae3b05160d697f88cfd0734c
          secret_key:
             934a9c2912fb49d5e4f0ff3e81dd8b0033aa227aa44e8bf7a60697a6dcff0b90
          proof_of_work_stamp: 874a325a463d6b6c1948eaa09252253ad9b2f1e01a4d6a7a
    runs:
      - octez_node
      - baker
      - accuser
      - vdf
    readiness_probe: false
    storage_size: 15Gi
  # Overwrite default values.yaml tezos-node
  rolling-node: null

smartRollupNodes:
  evm:
    operator_account: teztnetsbaker
    rollup_address: sr1RYurGZtN8KNSpkMcCt9CgWeUaNkzsAfXf
    ingress:
      # ingress details filled by pulumi
    evm_proxy:
      annotations:
        # sometimes evm proxy takes too long to initialize
        # because it depends on the rollup node which in turn
        # depends on the octez node to be available
        'pulumi.com/skipAwait': true
      ingress:
      # ingress details filled by pulumi
dalNodes:
  dal-bootstrap:
    bootstrapProfile: true
    node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
    storageSize: 15Gi
    ingress:
    # ingress details filled up by pulumi
    identity:
      peer_id: "idtP2sCN5G1DEb8jnRWKzuuuady3rN"
      public_key:
        "baefe8b7fb13708e859266b2ff33c71bfaceeb6bde01d7b829d81586fb00025c"
      secret_key:
        "e01819d7321a360369c2e9cbb738cd13592901163e4c4f21b17cf7081f78afc3"
      proof_of_work_stamp: "c10a73f331df5df498d5f0332611b3ec25334a8328f5c2b8"
  dal-dal1:
    attest_using_accounts:
      - teztnetsbaker
    storageSize: 15Gi
    node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
    ingress:
    # ingress details filled up by pulumi
    identity:
      peer_id: "idr42HkfCUcYYNBW51xUkobr1mxchY"
      public_key:
        "c2de27a3047a3a01f22523da8de69ce54ede3cdb001d23ca5038967f7c068c66"
      secret_key:
          "e68041663d0600f19d67b42f94d7dddcbd5f22db604b7f318b4ce17aec19ba2b"
      proof_of_work_stamp: "5f847aaa8f1624bf3e1861532947beeef3e9b4d509f06362"

dal_deploy_slot_injector:
  enabled: true
  inject_using_account: teztnetsbaker
  node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
  dal_node_rpc_url: http://dal-dal1:10732
  slot_size: 16384

bootstrap_peers: []
full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null
snapshot_source: https://snapshots.tezos.marigold.dev/api/tezos-snapshots.json
images: {}

# FIXME: does not work properly when several namespaces have it
# The dashboards get all mixed up together.
# serviceMonitor:
#   enabled: true
#   labels:
#     release: monitoring-96695a88

accounts:
  teztnetsbaker:
    # mv1UAzbGkMvuCr7ufR6Z4NxykCn2aj5qTUjm
    bootstrap_balance: "7500000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
    dal_node_rpc_url: http://dal-dal1:10732
  tf1:
    key: edpktnhkGfR4GWZ2BWthxB796zDQtcRDaiTDbUGMwXA9stoLqzPncb
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf2:
    key: edpkvJ4yYhB4VUv2QS3pW7dRVxs4n2gVRJakD5k3TDHPkuWMPxLU5t
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf3:
    key: edpktfnVodSwFtQdnRLYvWQmEmihP6NBndknAY7Ld2hnpFBXiLVL6v
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf4:
    key: edpkv5DKpGgMCLmxkCh2q4chNwZDsKykQe1A5MqQHvMSaka584C38x
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf5:
    key: edpkur3eJCphrFcopko2onAMu4PBv7q68TL7yWxN3mB3teLhgogioq
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  oxheadfree:
    # an account with a lot of money in it
    # mv1UBRZEJQ211zucHsXAn19FzZTeov3DSmbm
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public
  faucet:
    # faucet on teztnets.xyz platform
    # mv1NRjkhmeavqVVh716ephuXmaXGe7Y6UyzQ
    key: edpkvGYHoY5kwq13Ak6r4fLa1GGSHKJZVe7xJFV6ZgHwdZeaHy3WZj
    bootstrap_balance: "200000000000000"
    is_bootstrap_baker_account: false
  # SCORU test accounts
  # Contact: Yann Regis-Gianas
  scoru_rollup_operator:
    key: edpktnY9kXbEW1HjqDbQ4AG3hYkNunxHiRsZe72gEaHxddxNBtjG7B
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  scoru_enduser:
    key: edpkuet91oSH1Q9i4nGJRDjdsF9W7XcAteqLQe1VqSjtMHRtDpCVFp
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  # DAL Rich account
  # Contact: Francois Thire at Nomadic
  dal_rich_account:
    key: edpkuwL7MVYArfQN9jyR8pZTqmFGYFWTYhhF4F8KWjr2vB18ozTqbd
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
