node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_ITHACANET_2022-01-25T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesis1db77eJNeJ9
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2022-01-25T15:00:00Z"
  user_activated_upgrades:
    - level: 8191
      replacement_protocol: Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A
      # update to jakarta at the end of cycle 186, estimated to be on June 28th at 08:30 UTC
    - level: 765952
      replacement_protocol: PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY
        # update to kathmandu at the end of cycle 290, estimated to be on Sept 16 at 20:00 UTC
    - level: 1191936
      replacement_protocol: PtKathmankSpLLDALzWw7CGD2j2MtyveTwboEYokqUCP4a1LxMg
        # update to lima at the end of cycle 403, estimated to be on Dec 12
    - level: 1654784
      replacement_protocol: PtLimaPtLMwfNinJi9rCfDPWea8dFgTZ1MeJ9f1m2SRic6ayiwW

protocols:
  - command: PtLimaPt
    vote:
      liquidity_baking_toggle_vote: "on"

activation:
  protocol_hash: PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx
  protocol_parameters:
     preserved_cycles: 3
     blocks_per_cycle: 4096
     blocks_per_commitment: 32
     blocks_per_roll_snapshot: 256
     blocks_per_voting_period: 20480
     time_between_blocks:
       - "20"
       - "10"
     endorsers_per_block: 256
     hard_gas_limit_per_operation: "1040000"
     hard_gas_limit_per_block: "5200000"
     proof_of_work_threshold: "70368744177663"
     tokens_per_roll: "8000000000"
     seed_nonce_revelation_tip: "125000"
     origination_size: 257
     block_security_deposit: "640000000"
     endorsement_security_deposit: "2500000"
     baking_reward_per_endorsement:
       - "78125"
       - "11719"
     endorsement_reward:
       - "78125"
       - "52083"
     cost_per_byte: "250"
     hard_storage_limit_per_operation: "60000"
     quorum_min: 2000
     quorum_max: 7000
     min_proposal_quorum: 500
     initial_endorsers: 192
     delay_per_missing_endorsement: "2"
     liquidity_baking_escape_ema_threshold: 666667
     liquidity_baking_subsidy: '2500000'
     liquidity_baking_sunset_level: 10000000
     minimal_block_delay: '15'

nodes:
  tezos-baking-node:
    env:
      baker:
        BAKER_EXTRA_ARGS: "--operations-pool https://qc8esk5gp0.fbe-baker.midl.dev/operations-pool"
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - mavkit_node
      - baker
      - accuser
    storage_size: 400Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

bootstrap_peers:
  - ghostnet.smartpy.io
  - ghostnet.kaml.fr
  - ghostnet.boot.ecadinfra.com
  - ghostnet.stakenow.de:9733
  - ghostnet.tzboot.net


full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: "https://ghostnet-v15.xtz-shots.io/archive-tarball"

images:
  mavkit: mavrykdynamics/mavryk-protocol:v15.1

# We give:
accounts:
  oxheadbaker:
    # mv1UAzbGkMvuCr7ufR6Z4NxykCn2aj5qTUjm
    # edpkuYLienS3Xdt5c1vfRX1ibMxQuvfM67ByhJ9nmRYYKGAAoTq1UC
    bootstrap_balance: '1000000000000'
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  pirbo:
    # mv1C6KuPzs92LTENfXUPXq1oNxvaLjxJ9p8b
    key: edpkvaQpRgsSGPJSY91sjNArLMgpTUHmmfkvuSekwos43uze2H2EFM
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  andrewk:
    key: edpkvNGUd3xcBNmPWRbXJoS6WEvxu1BVoWjHr7ab7QoAJFFqhx9tkR
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  saroupille:
    # mv1CtdUBCLRpBziu4Xkuow3Xx2kjbhTieU5Z
    key: edpkvMBeXH4h8H97b8qfPkv2mA9TE6McfsffLGgG2Jg5nhUESaVt5J
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  mariano_ceibo:
    # mv1FV4mFvJJkSUwYPykDFtLesbhfVWkicpCT
    key: edpkv9xYGRddWjy9XMVeUq5d7gxWm3eVgYarrpmNW1qVvvRpmJq76G
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  fifthelement:
    key: edpkujqmLUVGNbSNZV7CBMdtXAMGTTwJDQoXp2aRGrotys51rYvaRi
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  coredump:
    # mv1K9acNerxTy6EpieyEEb4bQAr83JABwCJ8
    key: edpkttKzcNNCjanS2De2Nagnpg9Bk1SoNhxDC1hqCFvHHFjfeeBK1m
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  marco:
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  baketzforme:
    # mv1Szwqs9ZCFDig1nmq4Rg6XcGdoi1F4e5SF
    key: edpkuEoVW7HM9ehiec9exPfHrsFkT1f3jV8JxFWQHP23VX6K5EnVtD
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  vincent_xtzmaster:
    # mv1KjBsXcBauhqnPpFzMZVgN2mAf7mWCiWhJ
    key: edpkvaZQ6tt9XgJJTonjFpzwaqDV7RWUQMT7TmntBJ5yXmDsPb8T7L
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  daniel_jean:
    # mv1DYhW6VuDRTbQ8MvXQ11Nw5ee7WPF7KVaP
    key: edpkucJ7Nccy2wyaU4B2Ch4rxS4reiTfc7349pKtemcd4yLeXmbAwb
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  olivier_blockwatch:
    # mv1Qu7ZshVnDJJbdaGP1z2KQRc4cPdwRAFNQ
    key: edpktqRmZsGN2WEyghfqrZvn8c7xmA1xs3vDta71CsCjtHiSRMkG1z
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs:
    # mv1R7T3AKpmTEzkwPuUu14rewEjAz2qbT5tw
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs_2:
    # mv1EGkX33WgULe9voeXjD9xSNbZS5TtrUXgw
    key: edpkthQu5xeKjD9Dxh5tAf3f61z2Nteqk9xRVPVoZekk1CF738zbcJ
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  smartpy:
    # mv1EidjD8sWLCZeVqJdCfd1AXmTnkAEe1dGF
    key: edpkuyuJirNU14hEma1u7f3Qhx7uHZxzuXDyvmjRwaAsFFFqYGkzHx
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  neoktalabs_julien:
    # mv1DfaN4yBbWjAVut7oVi3wbtpoy3ZUAGDYF
    key: edpktnHv9X4PjoSHqzMGZf7oF6arxZbedxKTmEgcL6xS3XZ3TA1MUE
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  michael_kernaghan:
    # mv1SRWEiswZXAcpv3wA3CxQT8qVaMDuwZNEq
    key: edpkuRkcStobJ569XFxmE6edyRQQzMmtf4ZnmPkTPfSQnt6P3Nym2V
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  mack_baise:
    # mv1EfQPWVaqjFYQhXdGvMaBsPbtipJBp5cFF
    key: edpkvKJ9voHuSBi8TApVowCu7D8hQneXGWdEHuSEMDjQDyxD9h6PYk
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  richard_ayotte:
    # mv1XGPHyJWed9dDZHx44bwRFET2pkd5hbPBV
    key: edpkuty8oXRwNH5zRLfGkTyL2ukMVhGiht3qG8VNU5beD4NgP8X3gw
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  fredcy:
    # mv187nBvVX7iCc6bxozDokr1vzjqWiJk13rP
    key: edpkvTUqzRYhotk2YFnemLfBk8apvcSVNwTSxB6F6CaXUA64CRXgHN
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  functori:
    # mv1UHFmdi6hEUoi12qvY1zJmh2j3Nm1Vt9Pg
    key: edpkv2fhuhS4947m64XexZw2vMvr7C4zYTBFweXuWVCLbmaSqpFaT3
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  pierre_chambart:
    # mv1DHfJ66MfTpJtp7P8NEr9nBW6TKd1sGPgY
    key: edpkvGiC27B2WJRC6AoFS8wwSC4rrhnTULWxq53PkoJjJSRSCvFwJn
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  mystery_baker_6:
    # mv1SCriNPepisPkxm9koGknty1bN5qwhgtKs
    key: edpkupKuAv85MDjsfAEFeNMS4jHwkS1dT1dRajVwoYeSs6jEbwcTPm
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  primate_1:
    key: edpktuBstbzSXPY2Quht2ijPtn8Wz5K8FfCL8GyeDdKmqkrt3np8Xh
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  primate_2:
    key: edpkuYrv6f4zopEWWtiSVzfH3RqLVjj3tr73oipQGgz9yd971ksA32
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  primate_3:
    key: edpkuvPH36bzsLzo1YDPxiZpKPJHSmcDpTKMTtiTMgcJGYLQp1WvEo
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  oxheadfree:
    # an account with a lot of money in it
    # mv1UBRZEJQ211zucHsXAn19FzZTeov3DSmbm
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public
  mv1Fewfk:
    # mv1FewfkkANV9UrmmgqPdcCPwwV7XftdvhLS
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # mv185FmHGAimjbxkFEz8fcfeNHJ9pFwLquQW
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  julien:
    # julien.tesson@tezcore.com
    # for stress testing
    # mv1C666oQekupeXexgguj5AwnqK5mVRTKek6
    key: edpktnArvYkSArFUGiBN4cmDmor9qwyTFCbAKEMbeSdT3z563SdTXm
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000"
  tf:
    # mv3CTasxJUynvzBekpfsPhDTpvDsKMezU9Hd
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  jdsika:
    key: edpkutdFBe12UBzvgRKtAPbhQrpRA46oBSJCECeHswSLPzf6eAeqph
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  german:
    #  mv1FdnkStDVAwUpcNeruHcBf8bVnD6rvNSik
    key: edpkvG8RpyhnPi3ugWWvavsKwR79rb7iMvedeFNxBdyCvenTDZeC9n
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ping:
    key: edpkty9Zdoxxc8BCCseTaeKtBpAVctrzVmzhkj3dkgmbFkWduu4SCB
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ping2:
    key: edpkvZcJNTNG3q4A4N42eNPPCtUDT5jffMCYwiD7QLzRGZ4CQR8pyj
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  cryptodad:
    #  mv1RKNrCj5KNmJDkJ5aqLxAze1QHpPQ9iotY
    key: edpktk3ywyYujAUpAfWZwtNn9xRpVYDvRCd3EPGNyry9y9txUrnxhp
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  sirneb:
    #  mv18mWLUHZgKqzsUmVU9uaV5BXWngW844izL
    key: edpkuqjXrnDW2HAGj62ggEAMUp7o4Pv7V2saqTrXomuBQmrwjexViX
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
