accounts:
  oxheadbaker:
    # mv1UAzbGkMvuCr7ufR6Z4NxykCn2aj5qTUjm
    bootstrap_balance: "6700000000000"
    is_bootstrap_baker_account: true
    type: secret
    # key injected by pulumi
  oxheadfree:
    # an account with a lot of money in it
    # mv1UBRZEJQ211zucHsXAn19FzZTeov3DSmbm
    key: edpkubSgCoMjB2a6vPWRNRHfGa6HUFfFyEUKoEQhWC8osnav8QzBdJ
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
    type: public
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # mv185FmHGAimjbxkFEz8fcfeNHJ9pFwLquQW
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  mv1Fewfk:
    # mv1FewfkkANV9UrmmgqPdcCPwwV7XftdvhLS
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  rodrigo_quelhas:
    # mv1J5vxaVHv5PMoWwDbMmzwG1vNDUEjg9GUt
    key: edpkuDJ1GULsA4qX8LUy3ERSVkjnrJDaGaX9Q2Ea55RX2t2sZxc3iW
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  pirbo:
    # mv1C6KuPzs92LTENfXUPXq1oNxvaLjxJ9p8b
    key: edpkvaQpRgsSGPJSY91sjNArLMgpTUHmmfkvuSekwos43uze2H2EFM
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  andrewk:
    # mv1NszgcMUUhWe4XkWmupruw3DWuGEKi2EmL
    key: edpkvNGUd3xcBNmPWRbXJoS6WEvxu1BVoWjHr7ab7QoAJFFqhx9tkR
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  marco:
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  baketzforme:
    # mv1Szwqs9ZCFDig1nmq4Rg6XcGdoi1F4e5SF
    key: edpkuEoVW7HM9ehiec9exPfHrsFkT1f3jV8JxFWQHP23VX6K5EnVtD
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs:
    # mv1R7T3AKpmTEzkwPuUu14rewEjAz2qbT5tw
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs_2:
    # mv1EGkX33WgULe9voeXjD9xSNbZS5TtrUXgw
    key: edpkthQu5xeKjD9Dxh5tAf3f61z2Nteqk9xRVPVoZekk1CF738zbcJ
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  neoktalabs_julien:
      # mv1WqTpQa4mmxM21f9jTPXAn4WW19RRFkQ1L
      key: edpkuMRJewemWYJcfGUe3DLvemke3BZEitc3vVPbBFfnfwrynimuzY
      type: public
      is_bootstrap_baker_account: true
      bootstrap_balance: "1000000000000"
  michael_kernaghan:
    # mv1KeQch581fA6onNd7Tk4R6cczaAsZ6wXAQ
    key: edpkufKizMFA2EfbLdrUPLGcwe9EHad4MwtgGeVPCBP2x5VZeKHqsh
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  fredcy:
    # mv187nBvVX7iCc6bxozDokr1vzjqWiJk13rP
    key: edpkvTUqzRYhotk2YFnemLfBk8apvcSVNwTSxB6F6CaXUA64CRXgHN
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  baking_benjamins:
    # mv1KNR7BbSTcZKRoH6bKUgGnpZcytveswrjt
    key: edpkuT6dsU7krrQFBnk7c72EnrycvFeKQoL63EoiMz1AdQJGR9ux57
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  bake_buddy:
    # mv1LCGCRa8muQS6AC9voy63SDmzprsFSZTKV
    key: edpkvBxh9o7dFhrXGfxZKVuTTQHaS7YrorCaUndmLhqncU4ebKTxL9
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  tf:
    # mv3CTasxJUynvzBekpfsPhDTpvDsKMezU9Hd
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  tf2:
    # mv3DsEsWAVnhr4Vhxkod2yp6AJym2qA6hgYF
    key: p2pk67WaNJGC3VE4dhunamqKpMHXzxshf8REycJ5zvRf7HksaH3ir2F
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ping:
    #mv1W8agVWdfntqBZYm9nyJUfrKUVhMjPqESC
    key: edpkty9Zdoxxc8BCCseTaeKtBpAVctrzVmzhkj3dkgmbFkWduu4SCB
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ping_bob:
    #mv1AHfXjwzJ4NzWFjwdia9iBpWmLSu6rm2n8
    key: edpkvZcJNTNG3q4A4N42eNPPCtUDT5jffMCYwiD7QLzRGZ4CQR8pyj
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  pasqualepinto:
    # ???
    key: edpkugfNCoDerYV9pq1EfGgjX9mPk3uxX2wXhRz85dUNMtTUPnhjJE
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  pea:
    # mv184vc5V7cxfGUbAU42PsbFskkAtMezJ89F
    key: edpku2vFTjfziPbbViVqfHxVsmvTe5NZoaq6939Ex3eZCaSxkRTfpu
    type: public
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"

node_config_network:
  activation_account_name: oxheadbaker
  chain_name: TEZOS_JAKARTANET_2022-04-27T15:00:00Z
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesisbd16dciJxo9
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2022-04-27T15:00:00Z"
  user_activated_upgrades:
    - level: 8192
      replacement_protocol: PtJakart2xVj7pYXJBXrqHgd82rdkLey5ZeeGwDgPp9rhQUbSqY

activation:
  protocol_hash: Psithaca2MLRFYargivpo7YvUr7wUDqyxrdhC5CQq78mRvimz6A
  protocol_parameters:
    preserved_cycles: 3
    blocks_per_cycle: 4096
    blocks_per_commitment: 32
    blocks_per_stake_snapshot: 256
    blocks_per_voting_period: 4096
    hard_gas_limit_per_operation: '1040000'
    hard_gas_limit_per_block: '5200000'
    proof_of_work_threshold: '-1'
    tokens_per_roll: '6000000000'
    seed_nonce_revelation_tip: '125000'
    baking_reward_fixed_portion: '10000000'
    baking_reward_bonus_per_slot: '4286'
    endorsing_reward_per_slot: '2857'
    hard_storage_limit_per_operation: '60000'
    origination_size: 257
    cost_per_byte: '250'
    quorum_max: 7000
    quorum_min: 2000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: '2500000'
    liquidity_baking_sunset_level: 10000000
    liquidity_baking_escape_ema_threshold: 100000
    max_operations_time_to_live: 120
    minimal_block_delay: "15"
    delay_increment_per_round: "7"
    consensus_committee_size: 7000
    consensus_threshold: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    max_slashing_period: 2
    frozen_deposits_percentage: 10
    double_baking_punishment: "640000000"
    ratio_of_frozen_deposits_slashed_per_double_endorsement:
      numerator: 1
      denominator: 2

nodes:
  tezos-baking-node:
    instances:
      - bake_using_accounts:
          - oxheadbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
      - accuser
    readiness_probe: false
    storage_size: 160Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

bootstrap_peers:
  - jakartanet.kaml.fr
  - jakartanet.boot.ecadinfra.com

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: "https://jakartanet.xtz-shots.io/archive-tarball"

images:
  octez: tezos/tezos:v13.0

protocols:
  - command: 013-PtJakart
    vote:
      liquidity_baking_toggle_vote: "on"
