name: Publish Job Workflow

on:
  workflow_call:
    inputs:
      networks:
        required: true
        type: string
      testnets:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # install the python version needed
      - name: install pip pkgs
        run: |
          pip install PyYAML jinja2
      - run: |
          cat > networks.json <<EOF
          ${{ inputs.networks }}
          EOF
      - run: |
          cat > testnets.json <<EOF
          ${{ inputs.testnets }}
          EOF
      - name: generate release artifacts
        run: |
          python testnets_xyz_page/release.py
      - name: Deploy to testnets.mavryk.network
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/release
          enable_jekyll: true

      # Generate release artifacts for testnets.mavryk.network
      - name: Generate release artifacts for testnets.mavryk.network
        run: |
          python testnets_xyz_page/release.py
      # Temporary - deploy to testnets.mavryk.network
      - name: Rewrite and replace domain in jekyll site
        run: |
          sed -i 's/testnets.mavryk.network/testnets.mavryk.network/g' testnets_xyz_page/website/CNAME
          sed -i 's/testnets.mavryk.network/testnets.mavryk.network/g' testnets_xyz_page/website/_config.yml
          sed -i 's/testnets.mavryk.network/testnets.mavryk.network/g' testnets_xyz_page/website/_includes/header.html
          sed -i 's/testnets.mavryk.network/testnets.mavryk.network/g' testnets_xyz_page/website/index.markdown
      - name: Deploy to testnets.mavryk.network
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.TESTNETS_COM_DEPLOY_KEY }}
          publish_dir: ./target/release
          external_repository: mavryk-network/testnets
          enable_jekyll: true

      # End Temporary - deploy to testnets.mavryk.network
