name: Deploy On Push

on:
  push:
    branches:
      - main
      - mavryk-protocol-refactoring

jobs:
  # up:
  #   name: Pulumi Up
  #   uses: ./.github/workflows/_pulumi.yml
  #   secrets: inherit
  #   with:
  #     pulumi-command: up

  publish:
    name: testnets.mavryk.network build
    # needs: up
    uses: ./.github/workflows/_publish.yml
    secrets: inherit
    with:
      networks: ${{ vars.NETWORKS }}
      testnets: ${{ vars.TESTNETS }}
